[package]
name = "throbber-widgets-tui"
version = "0.1.1"
edition = "2021"
authors = ["arkbig"]
description = "This is a tui-rs widget that displays throbber."
readme = "README.md"
documentation = "https://docs.rs/throbber-widgets-tui/latest/throbber_widgets_tui/"
repository = "https://github.com/arkbig/throbber-widgets-tui"
license = "Zlib"
keywords = ["tui", "widgets"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tui = "0.19.0"

[dev-dependencies]
crossterm = "0.25.0"
