
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Audit
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        version: latest
        use-tool-cache: true

    - name: Audit
      run: cargo audit

    - name: Format
      run: cargo fmt --check --verbose

    - name: Lint
      run: cargo clippy

    - name: Documentation
      run: cargo doc

  build:
    needs: [ lint ]

    # name: Check for ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Build
      run: cargo check --verbose --release

    - name: Test
      run: cargo test --verbose
      continue-on-error: ${{ matrix.rust == 'nightly' }}
