on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MSRV: 1.56.1
  CARGO_TERM_COLOR: always

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Audit
      run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
    - name: Format
      run: cargo fmt --check --verbose
    - name: Lint
      run: cargo clippy
    - name: Documentation
      run: cargo doc

  build:
    needs: [ lint ]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - $MSRV
          - beta
          - nightly
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      run: |
        rustup toolchain install --profile minimal ${{ matrix.rust }}
        rustup override set ${{ matrix.rust }}
    - name: Build
      run: cargo check --verbose --release
    - name: Test
      run: cargo test --verbose
      continue-on-error: ${{ matrix.rust == 'nightly' }}
